services:
  mysql:
    image: mysql:8.0.44
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      # MYSQL_DATABASE: users_db
    volumes:
      # - mysql_data:/var/lib/mysql
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD --silent",
        ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  users-service:
    build: ./apps/users-service
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "dev-only-secret"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,users-service"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173"
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: users_db
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"

  catalog-service:
    build: ./apps/catalog-service
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "dev-only-secret"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,catalog-service"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173"
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: catalog_db
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8001:8001"

  gateway:
    build: ./apps/gateway
    depends_on:
      - users-service
      - catalog-service
    ports:
      - "8080:80"

  # web:
  #   build: ./apps/web
  #   environment:
  #     VITE_API_BASE_URL: "http://localhost:8080"
  #   ports:
  #     - "5173:5173"
